"""Backend-neutral Environment contracts and concrete registrations."""

from alphaapollo.common.environment.base import (
    ActType,
    BaseEnvironment,
    Env,
    EnvironmentContext,
    EnvironmentInitResult,
    EnvironmentLifecycleError,
    EnvironmentObservation,
    EnvironmentRuntimeError,
    EnvironmentSession,
    EnvironmentState,
    EnvironmentTransition,
    EnvStepOutput,
    ObsType,
    RuntimeEnvironmentAdapter,
)
from alphaapollo.common.environment.default import (
    Cleanup,
    DefaultEnvironment,
    ExecutorToolBridge,
    FakeToolBridge,
    GatewayToolBridge,
    RoutedToolBridge,
    TextOnlyToolBridge,
    ToolBridge,
    ToolBridgeResult,
)
from alphaapollo.common.environment.registry import (
    available_environments,
    create_environment,
    get_environment_factory,
    register_environment,
)
from alphaapollo.common.execution.workspace import WorkspaceLease, WorkspaceProvider

# Convenience re-exports. The canonical owner of capture and read-back
# contracts is ``alphaapollo.common.trajectory``.
from alphaapollo.common.trajectory.recorder import (
    EnvironmentCapture,
    EnvironmentCaptureKind,
    EnvironmentCaptureRecord,
    EnvironmentEventKind,
    EnvironmentEventSink,
    EnvironmentReplayStep,
    EnvironmentTrajectoryError,
    EnvironmentTrajectoryReader,
    EnvironmentTrajectoryView,
    NullEnvironmentEventSink,
    RecordedEnvironmentEvent,
    RecordingEnvironmentEventSink,
    SensitiveEnvironmentInputError,
    TrajectoryCaptureReader,
    TrajectoryCaptureStore,
    TrajectoryEnvironmentEventSink,
    ensure_safe_environment_input,
    sanitize_capture_value,
)

__all__ = [
    "ActType",
    "BaseEnvironment",
    "Cleanup",
    "DefaultEnvironment",
    "Env",
    "EnvironmentCapture",
    "EnvironmentCaptureKind",
    "EnvironmentCaptureRecord",
    "EnvironmentContext",
    "EnvironmentEventKind",
    "EnvironmentEventSink",
    "EnvironmentInitResult",
    "EnvironmentLifecycleError",
    "EnvironmentObservation",
    "EnvironmentReplayStep",
    "EnvironmentRuntimeError",
    "EnvironmentSession",
    "EnvironmentState",
    "EnvironmentTrajectoryError",
    "EnvironmentTrajectoryReader",
    "EnvironmentTrajectoryView",
    "EnvironmentTransition",
    "EnvStepOutput",
    "ExecutorToolBridge",
    "FakeToolBridge",
    "GatewayToolBridge",
    "NullEnvironmentEventSink",
    "ObsType",
    "RecordedEnvironmentEvent",
    "RecordingEnvironmentEventSink",
    "RoutedToolBridge",
    "RuntimeEnvironmentAdapter",
    "SensitiveEnvironmentInputError",
    "TextOnlyToolBridge",
    "ToolBridge",
    "ToolBridgeResult",
    "TrajectoryCaptureReader",
    "TrajectoryCaptureStore",
    "TrajectoryEnvironmentEventSink",
    "WorkspaceLease",
    "WorkspaceProvider",
    "available_environments",
    "create_environment",
    "ensure_safe_environment_input",
    "get_environment_factory",
    "register_environment",
    "sanitize_capture_value",
]
